### ISSUE TITLE
Update to grunt-sass

### ISSUE THREAD

**Issue by codenameEli** [WebDevStudios/_s#34]
Any specific reason why you use grunt-contrib-sass as opposed to [grunt-sass](https://github.com/sindresorhus/grunt-sass)? 

From a quick glance, I saw there was a large amount of <code>@imports</code> going on. We have had that slow us down during development. We have noticed a considerable speed up since we switched to grunt-sass, even if it only cuts 1 second off the watch.

I'd be glad to submit a pull request, just want to make sure before I do. Looks like a sweet setup!

**Comment by gregrickaby** [comment]
grunt-contrib-sass is more or less official. I have no issues switching to grunt-sass if everything compiles the same.

**Comment by codenameEli** [comment]
Cool, I will put in a PR soon after some testing.

**Comment by stacyk** [comment]
How about Node Sass instead so we can use Libsass? https://github.com/sass/node-sass 

And, I see they just released 3.0 tonight: https://github.com/sass/node-sass/releases/tag/v3.0.0

**Comment by codenameEli** [comment]
That looks pretty cool, I might try that on one of my projects and see the
pros/cons vs grunt-sass.

To clarify though, grunt-sass does use libsass, that is why its so much
faster.

Curiosity, would you keep a grunt files along with all of the other tasks
and run node-sass from there? I'm really curious about the implementation
of both and the use cases.

Thanks for sharing that, had no clue that exists.

**Comment by stacyk** [comment]
Sorry, in order for node-sass to compile in a grunt workflow, we should use something like Grunt-sass. I didn't see that it did use libsass until tonight. If we didn't use Grunt, we could use Node-Sass directly to compile sass using libsass instead of Ruby Sass.
